### PR TITLE
Fix loading validation issue of files tree

### LINKED ISSUE #190: Dropbox connection never completes UI loading procedure (spinner)
Howdie, thanks for sharing this fascinating and useful project! Yay!

Desktop v1.10.3 connects to Dropbox and create / open vault files just fine
Firefox extension v2.0.0 and Chrome extension v2.0.0 will connect to Dropbox okay, but seem unable to create / open any vault files (or even display them in the list)

The Chrome DevTools shows exactly one message in the Console

> [info] Received dropbox directory contents: / -> Array(0)

And there's the spinner in the "Choose or Create Vault" picker, that's where it stops and I can't seem to get any further

Is Dropbox connectivity working for anyone else? I think I might be doing something wrong, hmmm ...

### PR DESCRIPTION
**Pull request by gordroid**
This fix #190 and probably #194 too. I've tested it on firefox with dropbox only, don't have a way to test webdav.
 I couldn't find how to contrib, so please, let me know if you need me to change something.

Cheers

### CODE REVIEW

**Comment by gordroid** [comment]
I want to add that this validation will not support an empty array of files(as it wasn't supporting an empty array of directories) so this need to be revisited.

File: source/setup/components/RemoteFileTree.js [hunk 1]
```diff
@@ -231,7 +231,7 @@ class RemoteFileTree extends Component {
     render() {
         return (
             <Choose>
-                <When condition={this.props.rootDirectory && this.props.rootDirectory.directories.length > 0}>
+                <When condition={this.props.rootDirectory && this.props.rootDirectory.files.length > 0}>
```
Comment (sallar) [inline source/setup/components/RemoteFileTree.js]: Maybe instead of replacing The condition, add the other one as well with ||? `this.prop.rootDirectory && (this.props.rootDirectory.directories.length > 0 || this.props.rootDirectory.files.length > 0)`? This way we can ensure we cover both no files and no directories.

Comment (gordroid) [reply source/setup/components/RemoteFileTree.js]: Excellent, i think i saw one prop for that in the code, let me check if i can use that or i need to add a new one.

Comment (gordroid) [reply source/setup/components/RemoteFileTree.js]: I've reused the prop, it looks like it was meant for the condition this PR is fixing but it was not used for some reason. Let me know what you guys think.
Cheers!

File: source/setup/components/RemoteFileTree.js [hunk 2]
```diff
@@ -231,7 +232,7 @@ class RemoteFileTree extends Component {
     render() {
         return (
             <Choose>
-                <When condition={this.props.rootDirectory && this.props.rootDirectory.directories.length > 0}>
+                <When condition={this.props.rootDirectory && this.props.isLoading}>
```
Comment (sallar) [inline source/setup/components/RemoteFileTree.js]: I think this condition will be more effective and will fix all issues:

```suggestion
                <When condition={this.props.rootDirectory && this.props.rootDirectory.path}>
```

The `isLoading` props that are added can be removed now :) 
Thanks a lot for your help!

Comment (perry-mitchell) [reply source/setup/components/RemoteFileTree.js]: But is this always the case @sallar? Wouldn't checking network/loading be more accurate as you then don't need to care about the contents?

Comment (gordroid) [reply source/setup/components/RemoteFileTree.js]: I agree with you @perry-mitchell

**Comment by perry-mitchell** [comment]
This has stalled, so I'll merge, check and then go from there.

Thanks a lot @gordroid! We appreciate the help 🙏
